GetIt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('user_registration/', include('user_registration.urls')),
    path('user_logged/', include("django.contrib.auth.urls")),
    path('user_logged/', include("user_logged.urls")),
]

shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

user_logged/urls.py
from django.urls import path
from . import views

app_name = 'user_logged'

urlpatterns = [
    path('', views.user_login, name='login'),
    path('authenticate_user/', views.authenticate_user, name='authenticate_user'),
]

user_registration/urls.py
from django.urls import path
from . import views

app_name = 'user_registration'

urlpatterns = [
    path('', views.register_user, name='register_user'),
    ]

shop/models.py
from django.db import models

# Create your models here.

user_logged/models.py
from django.db import models

# Create your models here.

user_registration/models.py
from django.db import models

# Create your models here.

user_registration/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

shop/views.py
from django.shortcuts import render

TEMPLATE_DIRS = (
    'os.path.join(BASE_DIR, "templates"),'
)

def index(request):
    return render(request, 'index.html')

user_logged/views.py
from django.contrib.auth import authenticate, login
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

# Create your views here.

def user_login(request):
    """Logs in a user if the provided credentials are valid.

    If the login is successful, the user is redirected to the home page.
    If the login fails, the user is redirected to the login page with an error message.

    :param HttpRequest request: The HTTP request object
    :returns: The HTTP response object
    :rtype: HttpResponse
    """
    if request.method == 'POST':
        # Login form submitted
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            # Login successful
            login(request, user)
            
        else:
            # Login failed
            error_message = 'Invalid username or password'
            return render(request, 'authentication/login.html', {'error_message': error_message})
    else:
        # Display login form
        return render(request, 'authentication/login.html')

def authenticate_user(request):
    """Authenticates a user based on the provided credentials.

    If the authentication is successful, the user is redirected to the home page.
    If the authentication fails, the user is redirected to the login page.

    :param HttpRequest request: The HTTP request object
    :returns: The HTTP response object
    :rtype: HttpResponse
    """
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is None:
        return HttpResponseRedirect(
        reverse('user_logged:login')
    )
    else:
        login(request, user)
        return HttpResponseRedirect(
        reverse('index')
)

user_registration/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from .forms import RegistrationForm
from django.http import HttpResponse

# Create your views here.

def register_user(request):
    """Registers a new user with the provided user registration form and logs them in.

    :param request: The HTTP request object.
    :type request: django.http.HttpRequest
    :returns: If the form is valid, redirects the user to the 'index' view; otherwise, renders the registration form again with the validation errors.
    :rtype: django.shortcuts.redirect or django.shortcuts.render
    """
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
            #return HttpResponse("Registration successful")
    else:
        form = RegistrationForm()
    return render(request, 'user_registration/register.html', {'form': form})

shop/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Get It</title>

    <link rel="stylesheet" href="{% static 'shop/css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Shantell+Sans:ital,wght@1,300&display=swap');
        </style>
    
</head>

<body>
    <div class="top-nav-bar">
    <div class="search-box">
    <img src="{% static 'shop/Shop Logo.png' %}" alt="" class="logo">
    <input type="text" class="form-control" placeholder="Search for an item here ...">
    <span class="input-group-text"><i class="fa fa-search" aria-hidden="true"></i>></span>
    </div>

    <div class="menu-bar">
        <ul>
            <li><a href="#">Cart</a></li>
            <li><a href="{% url 'user_registration:register_user' %}">Sign up</a></li>
            <li><a href="{% url 'user_logged:login' %}">Log In</a></li>
        </ul>
    </div>
<div class="container">
    <h1 class="my-4">Welcome to our Online Store</h1>
    <div class="row">
      <div class="col-md-4 mb-4">
        <div class="card">
          <img src="{% static 'shop/bag.jpeg' %}" class="card-img-top product-img" alt="Kids Backpack">
          <div class="card-body">
            <h5 class="card-title">Product 1</h5>
            <p class="card-text">R199-99</p>
            <a href="#" class="btn btn-primary">Buy Now</a>
          </div>
        </div>
      </div>
      <div class="col-md-4 mb-4">
        <div class="card">
          <img src="{% static 'shop/bin.jpeg' %}" class="card-img-top product-img" alt="Room Bin">
          <div class="card-body">
            <h5 class="card-title">Room Bin</h5>
            <p class="card-text">R89-99</p>
            <a href="#" class="btn btn-primary">Buy Now</a>
          </div>
        </div>
      </div>
      <div class="col-md-4 mb-4">
        <div class="card">
          <img src="{% static 'shop/calc.jpeg' %}" class="card-img-top product-img" alt="Scientific Calculator">
          <div class="card-body">
            <h5 class="card-title">Scientific Calculator</h5>
            <p class="card-text">R320-00</p>
            <a href="#" class="btn btn-primary">Buy Now</a>
          </div>
        </div>
      </div>
      <div class="col-md-4 mb-4">
        <div class="card">
          <img src="{% static 'shop/pencil case.jpeg' %}" class="card-img-top product-img" alt="Pencil Case">
          <div class="card-body">
            <h5 class="card-title">Pencil Case</h5>
            <p class="card-text">R49-99</p>
            <a href="#" class="btn btn-primary">Buy Now</a>
          </div>
        </div>
      </div>
      <div class="col-md-4 mb-4">
        <div class="card">
          <img src="{% static 'shop/ruler.jpeg' %}" class="card-img-top product-img" alt="Metal Ruler">
          <div class="card-body">
            <h5 class="card-title">Metal Ruler</h5>
            <p class="card-text">R19-99</p>
            <a href="#" class="btn btn-primary">Buy Now</a>
          </div>
        </div>
      </div>
      <div class="col-md-4 mb-4">
        <div class="card">
          <img src="{% static 'shop/scissor.jpeg' %}" class="card-img-top product-img" alt="Scissor" id="">
          <div class="card-body">
            <h5 class="card-title">School Scissor</h5>
            <p class="card-text">R12-00</p>
            <a href="#" class="btn btn-primary">Buy Now</a>
          </div>
        </div>
      </div>
      <div class="col-md-4 mb-4">
        <div class="card">
          <img src="{% static 'shop/sharpener.jpeg' %}" class="card-img-top product-img" alt="Sharpener">
          <div class="card-body">
            <h5 class="card-title">Sharpener</h5>
            <p class="card-text">R8-99</p>
            <a href="#" class="btn btn-primary">Buy Now</a>
          </div>
        </div>
      </div>
      <div class="col-md-4 mb-4">
        <div class="card">
          <img src="{% static 'shop/fineliners.jpeg' %}" class="card-img-top product-img" alt="Fineliners">
          <div class="card-body">
            <h5 class="card-title">Staedler Fineliners</h5>
            <p class="card-text">R69-99</p>
            <a href="#" class="btn btn-primary">Buy Now</a>
          </div>
        </div>
      </div>
      <div class="col-md-4 mb-4">
        <div class="card">
          <img src="{% static 'shop/erasor.jpeg' %}" class="card-img-top product-img" alt="Eraser">
          <div class="card-body">
            <h5 class="card-title">Eraser</h5>
            <p class="card-text">R6-99</p>
            <a href="#" class="btn btn-primary">Buy Now</a>
          </div>
        </div>
      </div>
    <footer class="footer">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <form>
                <div class="form-group row">
                  <label for="name" class="col-sm-3 col-form-label">Name:</label>
                  <div class="col-sm-9">
                    <input type="text" class="form-control" id="name" placeholder="Enter your name">
                  </div>
                </div>
                <div class="form-group row">
                  <label for="email" class="col-sm-3 col-form-label">Email:</label>
                  <div class="col-sm-9">
                    <input type="email" class="form-control" id="email" placeholder="Enter your email">
                  </div>
                </div>
                <div class="form-group row">
                  <label for="phone" class="col-sm-3 col-form-label">Phone:</label>
                  <div class="col-sm-9">
                    <input type="tel" class="form-control" id="phone" placeholder="Enter your phone number">
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-sm-9 offset-sm-3">
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </div>
                </div>
              </form>
            </div>
            <div class="col-md-6">
                <img style="margin-left: 40px;" src="{% static 'shop/Shop Logo.png' %}" alt="" class="logo">
                <p style="margin-left: 20px;
                text-align: center  ;">
                    123 Balkan Street<br>Johanessburg, South Africa 12345<br>Phone: (+27) 123-4567<br>Email: info@example.com
                </p>
            </div>
          </div>
        </div>
      </footer>
    
</body>
</html>

user_logged/templates/authentication/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Login Page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'user_logged/css/login.css' %}">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Shantell+Sans:ital,wght@1,300&display=swap');
        </style>
</head>
<body>
    <h1>Login</h1>

    <form action="{% url 'user_logged:authenticate_user' %}" method="post">
        {% csrf_token %}

        <label>Username</label>
        <input type="text" name="username" placeholder="Username" required>
        <br/><br/>

        <label>Password</label>
        <input type="password" name="password" placeholder="Password" required>
        <br/><br/>
        
        <input type="submit" value="Login" />
        
    </form>

    <p>Don't have an account? <a href="{% url 'user_registration:register_user' %}">Register</a></p>
</body>
</html>

user_registration/templates/user_registration/register.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Register New User</title>
	<link rel="stylesheet" href="{% static 'user_registration/css/style.css' %}">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Shantell+Sans:ital,wght@1,300&display=swap');
        </style>
</head>
<body>
	<h1>Register New User</h1>
	<form method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Register</button>
	</form>
</body>
</html>